name: Deploy to Hostinger

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar SSH para acesso à VPS
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/mykeys.pem
          chmod 600 ~/.ssh/mykeys.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Gerar arquivo .env
      - name: Generate .env file
        run: |
          cat << EOF > .env
          VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}
          VITE_APP_HOST=${{ secrets.VITE_APP_HOST }}
          VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}
          BACKEND_URL=${{ secrets.BACKEND_URL }}
          ANALYTICS_GTAG=${{ secrets.ANALYTICS_GTAG }}
          ANALYTICS_APP_NAME=${{ secrets.ANALYTICS_APP_NAME }}
          EOF

      # Copiar arquivos para a VPS
      - name: Copy files to VPS
        run: |
          rsync -avz --exclude '.git' -e "ssh -i ~/.ssh/mykeys.pem -o ServerAliveInterval=60 -o ServerAliveCountMax=60" . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/roboticsmind

      # Executar Docker Compose na VPS via SSH
      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/mykeys.pem -o ServerAliveInterval=60 -o ServerAliveCountMax=60 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/roboticsmind
            docker compose -f docker-compose.yml down --remove-orphans
            docker system prune -f
            docker compose -f docker-compose.yml up -d --build
          EOF
          